from __future__ import annotations

import copy
import sys
from pathlib import Path

import pytest

TOOLS = Path(__file__).resolve().parents[2] / "tools"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import capability_status as capability  # noqa: E402


def _entry(
    capability_id: str,
    *,
    status: str,
    owner: str = "Core",
    delivery_scope: str = "integration",
    dependencies: list[str] | None = None,
    owner_disposition_ref: str = "",
) -> dict:
    implemented = status in {"implemented", "partially_implemented"}
    return {
        "id": capability_id,
        "name": capability_id.replace(".", " ").title(),
        "owner": owner,
        "delivery_scope": delivery_scope,
        "status": status,
        "summary": "Bounded test capability.",
        "dependencies": dependencies or [],
        "canonical_evidence": ["canonical.md"],
        "source_evidence": ["source.py"] if implemented else [],
        "test_evidence": ["test.py"] if implemented else [],
        "owner_disposition_ref": owner_disposition_ref,
        "superseded_by": "",
    }


def _registry(root: Path, *, publication_status: str = "definitive") -> dict:
    for name in ("canonical.md", "source.py", "test.py", "owner-review.md"):
        (root / name).write_text(name, encoding="utf-8")
    return {
        "schema_version": "capability_status_v1",
        "publication_status": publication_status,
        "owner_review_ref": "owner-review.md",
        "active_gate_id": "core.next",
        "entries": [
            _entry("core.base", status="implemented"),
            _entry("core.next", status="specified_future", dependencies=["core.base"]),
        ],
    }


def test_repository_registry_is_definitive_and_renderable() -> None:
    registry = capability.load_registry(capability.DEFAULT_REGISTRY)

    capability.validate_registry(registry)
    assert registry["publication_status"] == "definitive"
    assert "# Current State" in capability.render_registry(registry)


def test_definitive_registry_renders_active_gate_and_closed_statuses(tmp_path: Path) -> None:
    registry = _registry(tmp_path)

    rendered = capability.render_registry(registry, root=tmp_path)

    assert "Active gate: `core.next`" in rendered
    assert "`implemented`" in rendered
    assert "`specified_future`" in rendered
    assert "Generated by tools/capability_status.py" in rendered


def test_definitive_non_core_entry_requires_existing_owner_disposition(tmp_path: Path) -> None:
    registry = _registry(tmp_path)
    registry["entries"].append(
        _entry(
            "feature.audit",
            status="partially_implemented",
            owner="Audit Owner",
        )
    )

    with pytest.raises(capability.CapabilityStatusError, match="requires non-Core owner disposition"):
        capability.validate_registry(registry, root=tmp_path)

    (tmp_path / "audit-disposition.md").write_text("Accepted", encoding="utf-8")
    registry["entries"][-1]["owner_disposition_ref"] = "audit-disposition.md"
    capability.validate_registry(registry, root=tmp_path)


@pytest.mark.parametrize(
    ("mutation", "expected"),
    (
        ("unknown_dependency", "unknown dependency"),
        ("dependency_cycle", "dependency cycle"),
        ("missing_evidence", "does not exist"),
        ("implemented_without_tests", "requires source and test evidence"),
        ("active_dependency_incomplete", "active gate dependency is not implemented"),
    ),
)
def test_registry_rejects_mechanical_maturity_errors(
    tmp_path: Path,
    mutation: str,
    expected: str,
) -> None:
    registry = _registry(tmp_path)
    if mutation == "unknown_dependency":
        registry["entries"][1]["dependencies"] = ["core.unknown"]
    elif mutation == "dependency_cycle":
        registry["entries"][0]["dependencies"] = ["core.next"]
    elif mutation == "missing_evidence":
        registry["entries"][0]["source_evidence"] = ["missing.py"]
    elif mutation == "implemented_without_tests":
        registry["entries"][0]["test_evidence"] = []
    else:
        registry["entries"][0]["status"] = "partially_implemented"

    with pytest.raises(capability.CapabilityStatusError, match=expected):
        capability.validate_registry(copy.deepcopy(registry), root=tmp_path)
